const NOMBRE_HOJA_RENOVACIONES = "Renovaciones";
const NOMBRE_HOJA_RENOVACIONES_SOAT = "Renovaciones_SOAT";
const NOMBRE_HOJA_RENOVACIONES_VIDA_LEY = "Renovaciones_VIDA_LEY";
const NOMBRE_HOJA_RENOVACIONES_SCTR = "Renovaciones_SCTR";
const NOMBRE_HOJA_RENOVACIONES_VEHICULAR = "Renovaciones_VEHICULAR";
const NOMBRE_HOJA_EXPORT = NOMBRE_HOJA_RENOVACIONES;
const NOMBRE_HOJA_SEGUIMIENTO = "Seguimiento";
const NOMBRE_HOJA_LOG_ENVIOS = "Log_Envios";
const NOMBRE_HOJA_CONFIGURACION = "Configuracion";
const NOMBRE_HOJA_OPCIONES_SOAT = "Opciones_SOAT";
const NOMBRE_HOJA_OPCIONES_VEHICULAR = "Opciones_VEHICULAR";
const NOMBRE_HOJA_RESPUESTAS_SOAT = "Respuestas_SOAT";
const NOMBRE_HOJA_RESPUESTAS_VIDA_LEY = "Respuestas_VIDA_LEY";
const NOMBRE_HOJA_RESPUESTAS_SCTR = "Respuestas_SCTR";
const NOMBRE_HOJA_RESPUESTAS_VEHICULAR = "Respuestas_VEHICULAR";
const CONFIG_ENVIO = {
  ACTIVO: true,
  MAX_ENVIOS_DIA: 50
};

const CONFIG_REBOTES = {
  ACTIVO: true,
  CADA_HORAS: 1
};

const CONFIG_RESPUESTAS = {
  ACTIVO: true,
  CADA_HORAS: 1
};

const CONFIG_RECORDATORIOS = {
  ACTIVO: false,
  HORA: 10
};

const CONFIG_IA = {
  ACTIVO: false,
  PROVEEDOR: "GEMINI",
  MODELO: "gemini-3.5-flash",
  API_KEY_PROPERTY: "GEMINI_API_KEY",
  URL_INTERACTIONS: "https://generativelanguage.googleapis.com/v1beta/interactions"
};

const PRODUCTOS = {
  SOAT: "SOAT",
  VEHICULAR: "VEHICULAR",
  VIDA_LEY: "VIDA_LEY",
  SCTR: "SCTR",
  LAFT: "LAFT"
};

const HOJAS_RENOVACIONES_PRODUCTO = [
  {
    producto: PRODUCTOS.SOAT,
    hoja: NOMBRE_HOJA_RENOVACIONES_SOAT
  },
  {
    producto: PRODUCTOS.VIDA_LEY,
    hoja: NOMBRE_HOJA_RENOVACIONES_VIDA_LEY
  },
  {
    producto: PRODUCTOS.SCTR,
    hoja: NOMBRE_HOJA_RENOVACIONES_SCTR
  },
  {
    producto: PRODUCTOS.VEHICULAR,
    hoja: NOMBRE_HOJA_RENOVACIONES_VEHICULAR
  }
];

const HOJAS_OPCIONES_PRODUCTO = [
  {
    producto: PRODUCTOS.SOAT,
    hoja: NOMBRE_HOJA_OPCIONES_SOAT
  },
  {
    producto: PRODUCTOS.VEHICULAR,
    hoja: NOMBRE_HOJA_OPCIONES_VEHICULAR
  }
];

const HOJAS_RESPUESTAS_PRODUCTO = [
  {
    producto: PRODUCTOS.SOAT,
    hoja: NOMBRE_HOJA_RESPUESTAS_SOAT
  },
  {
    producto: PRODUCTOS.VIDA_LEY,
    hoja: NOMBRE_HOJA_RESPUESTAS_VIDA_LEY
  },
  {
    producto: PRODUCTOS.SCTR,
    hoja: NOMBRE_HOJA_RESPUESTAS_SCTR
  },
  {
    producto: PRODUCTOS.VEHICULAR,
    hoja: NOMBRE_HOJA_RESPUESTAS_VEHICULAR
  }
];

const INTENCIONES = {
  ACEPTA_RENOVACION: "ACEPTA_RENOVACION",
  SOLICITA_INFORMACION: "SOLICITA_INFORMACION",
  ENVIA_DOCUMENTOS: "ENVIA_DOCUMENTOS",
  SOLICITA_VALIDACION: "SOLICITA_VALIDACION",
  SOLICITA_CONTACTO: "SOLICITA_CONTACTO",
  NO_INTERESADO: "NO_INTERESADO",
  YA_RENOVO: "YA_RENOVO",
  RESPUESTA_NO_CLARA: "RESPUESTA_NO_CLARA"
};

const ESTADOS = {
  PENDIENTE_ENVIO: "PENDIENTE_ENVIO",
  ENVIADO: "ENVIADO",
  RESPONDIDO: "RESPONDIDO",
  RECORDATORIO_1_ENVIADO: "RECORDATORIO_1_ENVIADO",
  RECORDATORIO_2_ENVIADO: "RECORDATORIO_2_ENVIADO",
  ACEPTA_RENOVACION: "ACEPTA_RENOVACION",
  SOLICITA_INFORMACION: "SOLICITA_INFORMACION",
  ENVIA_DOCUMENTOS: "ENVIA_DOCUMENTOS",
  SOLICITA_VALIDACION: "SOLICITA_VALIDACION",
  SOLICITA_CONTACTO: "SOLICITA_CONTACTO",
  NO_INTERESADO: "NO_INTERESADO",
  YA_RENOVO: "YA_RENOVO",
  RESPUESTA_NO_CLARA: "RESPUESTA_NO_CLARA",
  REQUIERE_REVISION: "REQUIERE_REVISION",
  ERROR_ENVIO: "ERROR_ENVIO",
  ERROR_VALIDACION: "ERROR_VALIDACION",
  REBOTADO: "REBOTADO",
  OMITIDO: "OMITIDO",
  CERRADO: "CERRADO"
};
